# Generated by Django 5.0.6 on 2024-06-18 01:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('emcont_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Emergency Contact', primary_key=True, serialize=False)),
                ('emcont_name', models.CharField(max_length=200)),
                ('emcont_relationship', models.CharField(max_length=200)),
                ('emcont_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Guardian',
            fields=[
                ('parent_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Parent or Guardian', primary_key=True, serialize=False)),
                ('parent_fname', models.CharField(max_length=100)),
                ('parent_lname', models.CharField(max_length=100)),
                ('parent_address1', models.CharField(max_length=250)),
                ('parent_address2', models.CharField(max_length=250)),
                ('parent_city', models.CharField(max_length=100)),
                ('parent_state', models.CharField(max_length=100)),
                ('parent_zip', models.IntegerField()),
                ('parent_email', models.EmailField(max_length=100)),
                ('parent_phone1', models.CharField(max_length=20)),
                ('parent_phone2', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['parent_lname', 'parent_fname'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a Tutor', primary_key=True, serialize=False)),
                ('tutor_fname', models.CharField(max_length=100)),
                ('tutor_lname', models.CharField(max_length=100)),
                ('tutor_address1', models.CharField(max_length=250)),
                ('tutor_address2', models.CharField(max_length=250)),
                ('tutor_city', models.CharField(max_length=100)),
                ('tutor_state', models.CharField(max_length=100)),
                ('tutor_zip', models.IntegerField()),
                ('tutor_email', models.EmailField(max_length=100)),
                ('tutor_phone', models.CharField(max_length=20)),
                ('tutor_hrRate', models.IntegerField()),
                ('tutor_funFact', models.TextField(help_text='Enter a fun fact about yourself', max_length=1000)),
                ('tutor_exp', models.IntegerField()),
            ],
            options={
                'ordering': ['tutor_lname', 'tutor_fname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a Student', primary_key=True, serialize=False)),
                ('student_fname', models.CharField(max_length=100)),
                ('student_lname', models.CharField(max_length=100)),
                ('student_address1', models.CharField(max_length=250)),
                ('student_address2', models.CharField(max_length=250)),
                ('student_city', models.CharField(max_length=100)),
                ('student_state', models.CharField(max_length=100)),
                ('student_zip', models.IntegerField()),
                ('student_email', models.EmailField(max_length=100)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('emcont_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.emergencycontact')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.parent_guardian')),
            ],
            options={
                'ordering': ['student_lname', 'student_fname'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a Session', primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_duration', models.IntegerField()),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('session_location', models.CharField(max_length=200)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.student')),
                ('tutor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Payments', primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=200)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.session')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for subjects', primary_key=True, serialize=False)),
                ('subject_category', models.CharField(max_length=200)),
                ('subject_level', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=200)),
                ('tutor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for available times', primary_key=True, serialize=False)),
                ('avail_day', models.DateField(blank=True, null=True)),
                ('avail_time', models.TimeField(blank=True, null=True)),
                ('tutor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutoring.tutor')),
            ],
        ),
    ]
